### ISSUE TITLE
Make items atomic and set up as expandable library

### ISSUE THREAD

**Issue by olizilla** [tableflip/ipfs-ui-style-guide#2]
I see this as a guide. Not rules. That'd be somewhat counter to the sprit of the decentralised web.

I'd like to set up stylesheet with a all the ideas in this guide defined as single purpose / atomic css declarations. This could published to ipfs and re-used. It could be used with tachyons, or be a customised version of tachyons.

Next up I'd like to provide the values (type scale sizes, spacing, colours, font family) in a json file that can be consumed by a css-in-js theme provider, or any build process that can pull values from json. See: https://github.com/jxnblk/styled-system#configuration

After that, I imagine it as a growing library of ipfs components, built as compositions of these atoms, similar to http://tachyons.io/components/ or the output of https://compositor.io/lab/

At it's core, this repo wants to make it easy for devs to build ipfs apps that have clear, legible, possibly (subjectively) beautiful interfaces, without requiring explicit co-ordination or having to individually meditate on the infinite question of what is good design. It wants to provide a place for the design-focused to communicate with the algorithm-focused, and it wants to record the design language we create as we do. It wants to grow!

**Comment by jessicaschilling** [comment]
Closing in favor of the more global https://github.com/ipfs/ipfs-gui/issues/29 -- though the eventual implementation of that will probably want to find its living home in the UI style guide.
