### ISSUE TITLE
Swatches on README have different colour values

### ISSUE THREAD

**Issue by alanshaw** [tableflip/ipfs-ui-style-guide#5]
### README.md

![swatches](https://user-images.githubusercontent.com/152863/35329996-c34afc84-00f9-11e8-98b2-a2201742ec95.jpg)

### docs/index.html

![palette](https://user-images.githubusercontent.com/152863/35330008-d2984c64-00f9-11e8-86ab-5de9250e8ad8.jpg)

**Comment by olizilla** [comment]
Yep. The new palette isn't finalized yet. Will update the readme when it is.

**Comment by olizilla** [comment]
Readme colors are updated
